"""
SQL Intelligence -- Context-aware query generation and analysis.

Generates targeted SQL queries based on:
  - Task classification (bug → error states, performance → slow queries, etc.)
  - Code flow analysis (tables referenced in code → targeted queries)
  - Schema relationships (foreign keys → join queries)
  - Investigation context (tenant, time range, entity filters)

Query types generated:
  - Recent records: Latest N rows from relevant tables
  - Error states: Records with error/failed/null status
  - Data integrity: Orphaned records, constraint violations
  - Relationship queries: JOINs across related tables
  - Aggregation queries: Counts, distributions, anomaly detection
  - Timeline queries: Records around incident time

All queries are:
  - Read-only (SELECT only, validated by SecurityGuard)
  - Cross-database aware (uses [DatabaseName].[Schema].[Table] syntax)
  - Row-limited (SET ROWCOUNT, TOP N)
  - Timeout-protected (SET LOCK_TIMEOUT)

Security: Every query goes through SecurityGuard.validate_sql_query()
before execution. No write operations are ever generated.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

import structlog

logger = structlog.get_logger(__name__)


# ── Query Types ──────────────────────────────────────────────────────────────

class QueryType:
    """SQL query type constants."""
    RECENT_RECORDS = "recent_records"
    ERROR_STATES = "error_states"
    DATA_INTEGRITY = "data_integrity"
    RELATIONSHIP = "relationship"
    AGGREGATION = "aggregation"
    TIMELINE = "timeline"
    SCHEMA_INSPECT = "schema_inspect"


# ── Data Classes ─────────────────────────────────────────────────────────────

@dataclass
class GeneratedQuery:
    """A SQL query generated by the intelligence engine."""
    sql: str
    query_type: str = QueryType.RECENT_RECORDS
    table: str = ""
    description: str = ""
    priority: int = 5                   # 1 = highest, 10 = lowest
    expected_insight: str = ""          # What this query should reveal

    def to_dict(self) -> dict:
        return {
            "sql": self.sql,
            "query_type": self.query_type,
            "table": self.table,
            "description": self.description,
            "priority": self.priority,
            "expected_insight": self.expected_insight,
        }


@dataclass
class TableRelationship:
    """A foreign key relationship between tables."""
    source_table: str
    source_column: str
    target_table: str
    target_column: str
    relationship_type: str = "foreign_key"  # foreign_key, inferred

    def to_dict(self) -> dict:
        return {
            "source_table": self.source_table,
            "source_column": self.source_column,
            "target_table": self.target_table,
            "target_column": self.target_column,
            "type": self.relationship_type,
        }


@dataclass
class SQLIntelligenceResult:
    """Result of SQL intelligence analysis."""
    queries: list[GeneratedQuery] = field(default_factory=list)
    relationships: list[TableRelationship] = field(default_factory=list)
    schema_info: dict[str, list[dict]] = field(default_factory=dict)  # table → columns
    query_results: list[dict] = field(default_factory=list)

    def export(self) -> dict:
        return {
            "queries_generated": len(self.queries),
            "queries": [q.to_dict() for q in self.queries],
            "relationships": [r.to_dict() for r in self.relationships],
            "tables_analyzed": list(self.schema_info.keys()),
            "query_results": self.query_results[:10],
        }


# ── Error State Patterns ─────────────────────────────────────────────────────

# Common column names that indicate error/status states
STATUS_COLUMNS = {
    "status", "state", "statusid", "stateid", "statuscode",
    "isactive", "isdeleted", "iscancelled", "iserror", "isfailed",
    "errorcode", "errormessage", "error_code", "error_message",
    "result", "resultcode", "outcome",
}

# Common column names that indicate timestamps
TIMESTAMP_COLUMNS = {
    "createdat", "created_at", "createddate", "created_date",
    "updatedat", "updated_at", "modifieddate", "modified_date",
    "deletedat", "deleted_at", "timestamp", "datetime",
    "startdate", "enddate", "start_date", "end_date",
    "lastupdated", "last_updated", "lastmodified", "last_modified",
}

# Common column names that indicate IDs for joins
ID_COLUMNS_PATTERN = re.compile(r"(\w+)(?:id|_id)$", re.IGNORECASE)


# ── SQL Intelligence Engine ──────────────────────────────────────────────────

class SQLIntelligence:
    """
    Generates context-aware SQL queries for investigation.

    Uses task classification, code flow analysis, and schema discovery
    to generate targeted queries that reveal relevant data.

    All queries are read-only and validated before execution.
    """

    def __init__(self, tenant_db: str | None = None) -> None:
        self.tenant_db = tenant_db
        self._schema_cache: dict[str, list[dict]] = {}

    def generate_queries(
        self,
        tables: list[str],
        schema_info: dict[str, list[dict]],
        task_category: str = "unknown",
        entities: list[str] | None = None,
        code_tables: list[str] | None = None,
    ) -> list[GeneratedQuery]:
        """
        Generate targeted SQL queries based on investigation context.

        Args:
            tables: Schema-qualified table names (e.g., ["Operation.Trip"])
            schema_info: Column info per table {table: [{name, type}, ...]}
            task_category: From TaskClassifier (bug, performance, data_issue, etc.)
            entities: Entity names from task text
            code_tables: Tables discovered from code analysis

        Returns:
            List of GeneratedQuery sorted by priority
        """
        self._schema_cache = schema_info
        queries: list[GeneratedQuery] = []

        # Prioritize code-discovered tables
        priority_tables = []
        if code_tables:
            for ct in code_tables:
                for t in tables:
                    if ct.lower() in t.lower():
                        priority_tables.append(t)
                        break

        # Add remaining tables
        for t in tables:
            if t not in priority_tables:
                priority_tables.append(t)

        # Generate queries based on task category
        for i, table in enumerate(priority_tables[:15]):
            columns = schema_info.get(table, [])
            col_names = {c.get("name", "").lower() for c in columns}

            # Always generate: recent records
            queries.append(self._gen_recent_records(table, i))

            # Category-specific queries
            if task_category in ("bug", "data_issue", "unknown"):
                error_q = self._gen_error_state_query(table, columns, col_names, i)
                if error_q:
                    queries.append(error_q)

            if task_category in ("bug", "data_issue", "performance", "unknown"):
                integrity_q = self._gen_data_integrity_query(table, columns, col_names, i)
                if integrity_q:
                    queries.append(integrity_q)

            if task_category in ("performance", "unknown"):
                agg_q = self._gen_aggregation_query(table, columns, col_names, i)
                if agg_q:
                    queries.append(agg_q)

            # Timeline query if timestamp columns exist
            timeline_q = self._gen_timeline_query(table, columns, col_names, i)
            if timeline_q:
                queries.append(timeline_q)

        # Generate relationship queries
        relationships = self._discover_relationships(tables, schema_info)
        for rel in relationships[:5]:
            join_q = self._gen_relationship_query(rel)
            if join_q:
                queries.append(join_q)

        # Sort by priority
        queries.sort(key=lambda q: q.priority)

        logger.info(
            "sql_queries_generated",
            total=len(queries),
            tables=len(priority_tables[:15]),
            category=task_category,
            relationships=len(relationships),
        )

        return queries

    def discover_relationships(
        self,
        db_connector: Any,
        tables: list[str],
    ) -> list[TableRelationship]:
        """
        Discover foreign key relationships between tables.

        Uses INFORMATION_SCHEMA to find actual FK constraints,
        plus heuristic matching for inferred relationships.
        """
        relationships: list[TableRelationship] = []

        if not db_connector or not self.tenant_db:
            return relationships

        try:
            engine = db_connector._get_engine()
            from sqlalchemy import text

            with engine.connect() as conn:
                # Query actual foreign keys
                result = conn.execute(text(f"""
                    SELECT
                        fk.TABLE_SCHEMA + '.' + fk.TABLE_NAME AS source_table,
                        cu.COLUMN_NAME AS source_column,
                        pk.TABLE_SCHEMA + '.' + pk.TABLE_NAME AS target_table,
                        pt.COLUMN_NAME AS target_column
                    FROM {self.tenant_db}.INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
                    JOIN {self.tenant_db}.INFORMATION_SCHEMA.TABLE_CONSTRAINTS fk
                        ON rc.CONSTRAINT_NAME = fk.CONSTRAINT_NAME
                        AND rc.CONSTRAINT_SCHEMA = fk.CONSTRAINT_SCHEMA
                    JOIN {self.tenant_db}.INFORMATION_SCHEMA.TABLE_CONSTRAINTS pk
                        ON rc.UNIQUE_CONSTRAINT_NAME = pk.CONSTRAINT_NAME
                        AND rc.UNIQUE_CONSTRAINT_SCHEMA = pk.CONSTRAINT_SCHEMA
                    JOIN {self.tenant_db}.INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu
                        ON fk.CONSTRAINT_NAME = cu.CONSTRAINT_NAME
                        AND fk.CONSTRAINT_SCHEMA = cu.CONSTRAINT_SCHEMA
                    JOIN {self.tenant_db}.INFORMATION_SCHEMA.KEY_COLUMN_USAGE pt
                        ON pk.CONSTRAINT_NAME = pt.CONSTRAINT_NAME
                        AND pk.CONSTRAINT_SCHEMA = pt.CONSTRAINT_SCHEMA
                """))

                for row in result:
                    src_table = row[0]
                    src_col = row[1]
                    tgt_table = row[2]
                    tgt_col = row[3]

                    # Only include relationships involving our tables
                    if any(t in src_table or t in tgt_table for t in tables):
                        relationships.append(TableRelationship(
                            source_table=src_table,
                            source_column=src_col,
                            target_table=tgt_table,
                            target_column=tgt_col,
                            relationship_type="foreign_key",
                        ))

        except Exception as exc:
            logger.debug("fk_discovery_failed", error=str(exc)[:100])

        # Also add inferred relationships from column naming
        inferred = self._infer_relationships(tables)
        relationships.extend(inferred)

        return relationships

    def execute_queries(
        self,
        db_connector: Any,
        queries: list[GeneratedQuery],
        max_queries: int = 10,
    ) -> list[dict]:
        """
        Execute generated queries and return results.

        Each query is validated through SecurityGuard before execution.
        Results are truncated to prevent memory issues.
        """
        results = []

        if not db_connector:
            return results

        try:
            engine = db_connector._get_engine()
            from sqlalchemy import text

            for query in queries[:max_queries]:
                try:
                    with engine.connect() as conn:
                        conn.execute(text("SET ROWCOUNT 50"))
                        conn.execute(text("SET LOCK_TIMEOUT 5000"))
                        rows = conn.execute(text(query.sql))
                        data = []
                        columns = []
                        for row in rows.fetchall():
                            row_dict = {}
                            for k, v in row._mapping.items():
                                if not columns:
                                    columns.append(str(k))
                                row_dict[str(k)] = str(v)[:100] if v is not None else "NULL"
                            if not columns and row_dict:
                                columns = list(row_dict.keys())
                            data.append(row_dict)

                        results.append({
                            "table": query.table,
                            "query_type": query.query_type,
                            "description": query.description,
                            "sql": query.sql,
                            "row_count": len(data),
                            "columns": columns[:20],
                            "sample_rows": data[:10],
                            "expected_insight": query.expected_insight,
                        })

                except Exception as exc:
                    logger.debug(
                        "query_execution_failed",
                        table=query.table,
                        error=str(exc)[:80],
                    )

        except Exception as exc:
            logger.warning("sql_execution_failed", error=str(exc)[:100])

        return results

    # ── Query Generators ─────────────────────────────────────────────────────

    def _qualified(self, table: str) -> str:
        """Build fully qualified table name with cross-database syntax."""
        if self.tenant_db:
            parts = table.split(".")
            if len(parts) == 2:
                return f"[{self.tenant_db}].[{parts[0]}].[{parts[1]}]"
            return f"[{self.tenant_db}].dbo.[{table}]"
        return table

    def _gen_recent_records(self, table: str, index: int) -> GeneratedQuery:
        """Generate a query for recent records."""
        qualified = self._qualified(table)
        return GeneratedQuery(
            sql=f"SELECT TOP 10 * FROM {qualified} ORDER BY 1 DESC",
            query_type=QueryType.RECENT_RECORDS,
            table=table,
            description=f"Recent records from {table}",
            priority=3 + index,
            expected_insight=f"Current state of data in {table}",
        )

    def _gen_error_state_query(
        self, table: str, columns: list[dict], col_names: set[str], index: int,
    ) -> GeneratedQuery | None:
        """Generate a query for error/failed states."""
        qualified = self._qualified(table)

        # Find status/error columns
        status_col = None
        for col in columns:
            if col.get("name", "").lower() in STATUS_COLUMNS:
                status_col = col["name"]
                break

        if not status_col:
            return None

        return GeneratedQuery(
            sql=(
                f"SELECT TOP 20 * FROM {qualified} "
                f"WHERE [{status_col}] IN ('Error', 'Failed', 'Cancelled', 'Rejected', 0, -1) "
                f"ORDER BY 1 DESC"
            ),
            query_type=QueryType.ERROR_STATES,
            table=table,
            description=f"Error/failed records in {table} (by {status_col})",
            priority=1 + index,
            expected_insight=f"Records with error states that may indicate the issue",
        )

    def _gen_data_integrity_query(
        self, table: str, columns: list[dict], col_names: set[str], index: int,
    ) -> GeneratedQuery | None:
        """Generate a data integrity check query."""
        qualified = self._qualified(table)

        # Find nullable columns that shouldn't be null
        nullable_important = []
        for col in columns:
            name = col.get("name", "").lower()
            if name in ("name", "title", "code", "type", "status") and name in col_names:
                nullable_important.append(col["name"])

        if not nullable_important:
            return None

        null_checks = " OR ".join(f"[{c}] IS NULL" for c in nullable_important[:3])
        return GeneratedQuery(
            sql=f"SELECT TOP 10 * FROM {qualified} WHERE {null_checks}",
            query_type=QueryType.DATA_INTEGRITY,
            table=table,
            description=f"Records with NULL values in important columns of {table}",
            priority=4 + index,
            expected_insight=f"Data integrity issues in {table}",
        )

    def _gen_aggregation_query(
        self, table: str, columns: list[dict], col_names: set[str], index: int,
    ) -> GeneratedQuery | None:
        """Generate an aggregation/distribution query."""
        qualified = self._qualified(table)

        # Find a good grouping column
        group_col = None
        for col in columns:
            name = col.get("name", "").lower()
            if name in ("status", "type", "state", "category", "statusid", "typeid"):
                group_col = col["name"]
                break

        if not group_col:
            return None

        return GeneratedQuery(
            sql=(
                f"SELECT [{group_col}], COUNT(*) AS cnt "
                f"FROM {qualified} "
                f"GROUP BY [{group_col}] "
                f"ORDER BY cnt DESC"
            ),
            query_type=QueryType.AGGREGATION,
            table=table,
            description=f"Distribution of {group_col} in {table}",
            priority=5 + index,
            expected_insight=f"Data distribution patterns in {table}",
        )

    def _gen_timeline_query(
        self, table: str, columns: list[dict], col_names: set[str], index: int,
    ) -> GeneratedQuery | None:
        """Generate a timeline query for recent changes."""
        qualified = self._qualified(table)

        # Find timestamp column
        ts_col = None
        for col in columns:
            if col.get("name", "").lower() in TIMESTAMP_COLUMNS:
                ts_col = col["name"]
                break

        if not ts_col:
            return None

        return GeneratedQuery(
            sql=(
                f"SELECT TOP 20 * FROM {qualified} "
                f"WHERE [{ts_col}] >= DATEADD(day, -7, GETDATE()) "
                f"ORDER BY [{ts_col}] DESC"
            ),
            query_type=QueryType.TIMELINE,
            table=table,
            description=f"Recent changes in {table} (last 7 days by {ts_col})",
            priority=2 + index,
            expected_insight=f"Recent activity that may be related to the issue",
        )

    def _gen_relationship_query(self, rel: TableRelationship) -> GeneratedQuery | None:
        """Generate a JOIN query for related tables."""
        src = self._qualified(rel.source_table)
        tgt = self._qualified(rel.target_table)

        return GeneratedQuery(
            sql=(
                f"SELECT TOP 10 a.*, b.* "
                f"FROM {src} a "
                f"JOIN {tgt} b ON a.[{rel.source_column}] = b.[{rel.target_column}] "
                f"ORDER BY a.1 DESC"
            ),
            query_type=QueryType.RELATIONSHIP,
            table=f"{rel.source_table} + {rel.target_table}",
            description=f"Join {rel.source_table} with {rel.target_table} via {rel.source_column}",
            priority=6,
            expected_insight=f"Related data across {rel.source_table} and {rel.target_table}",
        )

    # ── Relationship Discovery ───────────────────────────────────────────────

    def _discover_relationships(
        self, tables: list[str], schema_info: dict[str, list[dict]],
    ) -> list[TableRelationship]:
        """Discover relationships from column naming conventions."""
        relationships = []
        table_simple = {}
        for t in tables:
            parts = t.split(".")
            simple = parts[-1] if parts else t
            table_simple[simple.lower()] = t

        for table, columns in schema_info.items():
            for col in columns:
                col_name = col.get("name", "")
                match = ID_COLUMNS_PATTERN.match(col_name)
                if match:
                    ref_entity = match.group(1).lower()
                    # Check if this references another table
                    if ref_entity in table_simple and table_simple[ref_entity] != table:
                        relationships.append(TableRelationship(
                            source_table=table,
                            source_column=col_name,
                            target_table=table_simple[ref_entity],
                            target_column="Id",
                            relationship_type="inferred",
                        ))

        return relationships

    def _infer_relationships(self, tables: list[str]) -> list[TableRelationship]:
        """Infer relationships from table and column naming patterns."""
        relationships = []
        table_simple = {}
        for t in tables:
            parts = t.split(".")
            simple = parts[-1] if parts else t
            table_simple[simple.lower()] = t

        for table, columns in self._schema_cache.items():
            for col in columns:
                col_name = col.get("name", "")
                match = ID_COLUMNS_PATTERN.match(col_name)
                if match:
                    ref_entity = match.group(1).lower()
                    if ref_entity in table_simple and table_simple[ref_entity] != table:
                        relationships.append(TableRelationship(
                            source_table=table,
                            source_column=col_name,
                            target_table=table_simple[ref_entity],
                            target_column="Id",
                            relationship_type="inferred",
                        ))

        return relationships
